### PR TITLE
1px line on the side of ajfrown

### PR DESCRIPTION
**Pull request by sylae**
Even if she is worst pony, that's not a very nice thing to have.

Fix courtesy @Nebedia

### CODE REVIEW

**Comment by cburschka** [comment]
I'm not really seeing it, but I'm on a phone screen in bad lighting. Which side and what color? Does it have a high alpha?

**Comment by Nebedia** [comment]
It's hard to see, but the right side of :ajfrown: had a line of 5% CC9957 and some other colors. Probably due bad cropping on whatever pack they came in. So I replaced it with full transparency.

**Comment by Nebedia** [comment]
If you post it in the chat on a black background it's be easier to see.

**Comment by cburschka** [comment]
Yep, now I see it. Thanks!

**Pull request merged**
